version: '3.7'
services:
    symfony:
      build: .
      environment:
        APP_SECRET: "99fdd70735dc3d295670ae0a57e6f8e9"
        DATABASE_URL: "postgresql://main:main@database:5432/main?serverVersion=13&charset=utf8"
      ports:
        - '80'
    database:
      image: 'postgres:alpine'
      environment:
        POSTGRES_PASSWORD: main
        POSTGRES_USER: main
        POSTGRES_DB: main
