apiVersion: apps/v1
kind: Pod 
metadata:
  name: symfony
  namespace: apjgel-test 
spec:
  selector:
    matchLabels:
      app: symfony 
  containers:
  - name: symfony-dn
    image: {{ docker_image }} 
    command: ["bin/console"]
    args: ["doctrine:migrations:migrate", "-n"]
  restartPolicy: OnFailure
