apiVersion: v1
kind: Namespace
metadata:
  name: apjgel
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: apjgel
  labels:
    app: postgres
data:
  POSTGRES_DB: main 
  POSTGRES_USER: main
  POSTGRES_PASSWORD: main
---
apiVersion: v1
kind: Service
metadata:
  name: symfony 
  namespace: apjgel
spec:
  selector:
    app: symfony 
  ports:
  - name: http
    protocol: TCP
    port: 80
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: apjgel
spec:
  selector:
    app: postgres 
  ports:
  - name: http
    protocol: TCP
    port: 5432 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: symfony
  namespace: apjgel
spec:
  selector:
    matchLabels:
      app: symfony 
  template:
    metadata:
      labels:
        app: symfony 
    spec:
      containers:
      - name: symfony
        image: {{ docker_image }} 
        ports:
        - containerPort: 80 
          name: symfony
        env:
          - name: APP_SECRET
            value: "99fdd70735dc3d295670ae0a57e6f8e9"
          - name: DATABASE_URL
            value: "postgresql://main:main@postgres:5432/main?serverVersion=13&charset=utf8"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: apjgel
spec:
  selector:
    matchLabels:
      app: postgres 
  template:
    metadata:
      labels:
        app: postgres 
    spec:
      containers:
      - name: postgres
        image: postgres:alpine
        ports:
        - containerPort: 5432 
          name: postgres 
        env:
          - name: POSTGRES_DB
            value: main 
          - name: POSTGRES_USER
            value: main
          - name: POSTGRES_PASSWORD
            value: main

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: symfony 
  namespace: apjgel
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`apjgel.cloudlol.lol`)
      kind: Rule
      services:
        - name: symfony
          port: 80
  tls:
    certResolver: default

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: symfony80
  namespace: apjgel
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`apjgel.cloudlol.lol`)
      kind: Rule
      services:
        - name: symfony
          port: 80

