apiVersion: v1
kind: Pod 
metadata:
  name: symfony
  namespace: apjgel-test 
spec:
  containers:
  - name: symfony-db
    image: {{ docker_image }} 
    command: ["bin/console"]
    args: ["doctrine:migrations:migrate", "-n"]
  restartPolicy: OnFailure
