name: "CI"

on:
   pull_request:
   push:
       branches:
           - 'master'

env:
   fail-fast: true
   DATABASE_URL: ${{ secrets.DATABASE_URL }}

jobs:
   test:
       runs-on: 'ubuntu-latest'
       # Service containers to run with `container-job`
       services:
         # Label used to access the service container
         postgres:
            # Docker Hub image
            image: postgres
            # Provide the password for postgres
            env:
                POSTGRES_USER: main
                POSTGRES_PASSWORD: main
                POSTGRES_DB: main
           # Set health checks to wait until postgres has started
            options: >-
                --health-cmd pg_isready
                --health-interval 10s
                --health-timeout 5s
                --health-retries 5
            ports:
                # Maps tcp port 5432 on service container to the host
                - 5432:5432
       steps:
           - name: "Checkout code"
             uses: actions/checkout@v2.3.3

           - name: "Install PHP with extensions"
             uses: shivammathur/setup-php@2.7.0
             with:
                 coverage: "none"
                 extensions: "intl, mbstring, pdo_pgsql"
                 php-version: '8.0'
                 tools: composer:v2

           - name: "Set composer cache directory"
             id: composer-cache
             run: echo "::set-output name=dir::$(composer config cache-files-dir)"

           - name: "Cache composer"
             uses: actions/cache@v2.1.2
             with:
                 path: ${{ steps.composer-cache.outputs.dir }}
                 key: composer-${{ hashFiles('composer.json') }}
                 restore-keys: composer-

           - name: "Composer install"
             run: composer install

           - name: "Install Node deps"
             run: |
                yarn install
                yarn build

           - name: "Run migrations (init db)"
             run: bin/console doctrine:migrations:migrate

           - name: "Load fixtures (init db)"
             run: bin/console doctrine:fixtures:load

           - name: "Install PHPUnit for PHP 8"
             run: vendor/bin/simple-phpunit install

           - name: "PHPUnit version"
             run: vendor/bin/simple-phpunit --version

           - name: "Run tests"
             run: vendor/bin/simple-phpunit
